"""
utils.py — Utility Functions
Handles: CSV export, PDF report generation, portfolio config save/load,
         auto-insights, research mode text.
"""

import io
import json
import numpy as np
import pandas as pd
from datetime import datetime


# ─── CSV Export ───────────────────────────────────────────────────────────────

def export_prices_csv(prices: pd.DataFrame) -> bytes:
    buf = io.StringIO()
    prices.to_csv(buf)
    return buf.getvalue().encode()


def export_returns_csv(returns: pd.DataFrame) -> bytes:
    buf = io.StringIO()
    returns.to_csv(buf)
    return buf.getvalue().encode()


def export_weights_csv(weights: np.ndarray, tickers: list[str], name: str = "portfolio") -> bytes:
    df = pd.DataFrame({"ticker": tickers, "weight": weights})
    df = df.sort_values("weight", ascending=False)
    buf = io.StringIO()
    df.to_csv(buf, index=False)
    return buf.getvalue().encode()


def export_backtest_csv(equity: pd.Series, daily_returns: pd.Series) -> bytes:
    df = pd.DataFrame({"equity": equity, "daily_return": daily_returns})
    buf = io.StringIO()
    df.to_csv(buf)
    return buf.getvalue().encode()


# ─── PDF Report ───────────────────────────────────────────────────────────────

def generate_pdf_report(
    title: str,
    metrics_dict: dict,
    weights: np.ndarray,
    tickers: list[str],
    rmt_info: dict,
) -> bytes:
    """
    Generate a simple PDF report using fpdf2.
    Returns bytes of the PDF file.
    """
    try:
        from fpdf import FPDF

        class PDF(FPDF):
            def header(self):
                self.set_font("Courier", "B", 14)
                self.set_text_color(0, 212, 255)
                self.cell(0, 10, "EigenPortfolio — Quant Research Report", ln=True, align="C")
                self.set_draw_color(31, 45, 69)
                self.line(10, self.get_y(), 200, self.get_y())
                self.ln(4)

            def footer(self):
                self.set_y(-15)
                self.set_font("Courier", "I", 8)
                self.set_text_color(100, 116, 139)
                self.cell(0, 10, f"Generated by EigenPortfolio | Made by Sourish Dey | Page {self.page_no()}", align="C")

        pdf = PDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pdf.set_fill_color(10, 14, 26)
        pdf.rect(0, 0, 210, 297, "F")

        # Title
        pdf.set_font("Courier", "B", 18)
        pdf.set_text_color(0, 212, 255)
        pdf.cell(0, 14, title, ln=True, align="C")
        pdf.set_font("Courier", "", 9)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 6, f"Report generated: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}", ln=True, align="C")
        pdf.ln(6)

        # RMT Info
        pdf.set_font("Courier", "B", 11)
        pdf.set_text_color(124, 58, 237)
        pdf.cell(0, 8, "Random Matrix Theory Summary", ln=True)
        pdf.set_font("Courier", "", 9)
        pdf.set_text_color(226, 232, 240)
        for k, v in rmt_info.items():
            pdf.cell(0, 6, f"  {k}: {v}", ln=True)
        pdf.ln(4)

        # Performance Metrics
        pdf.set_font("Courier", "B", 11)
        pdf.set_text_color(0, 212, 255)
        pdf.cell(0, 8, "Performance Metrics", ln=True)
        pdf.set_font("Courier", "", 9)
        pdf.set_text_color(226, 232, 240)
        for strat, m in metrics_dict.items():
            pdf.set_font("Courier", "B", 9)
            pdf.set_text_color(16, 185, 129)
            pdf.cell(0, 7, f"  [{strat}]", ln=True)
            pdf.set_font("Courier", "", 8)
            pdf.set_text_color(226, 232, 240)
            for k, v in m.items():
                val = f"{v:.4f}" if isinstance(v, float) else str(v)
                pdf.cell(0, 5, f"    {k}: {val}", ln=True)
        pdf.ln(4)

        # Top Holdings
        pdf.set_font("Courier", "B", 11)
        pdf.set_text_color(0, 212, 255)
        pdf.cell(0, 8, "Top Portfolio Holdings", ln=True)
        pdf.set_font("Courier", "", 8)
        pdf.set_text_color(226, 232, 240)
        df = pd.DataFrame({"Ticker": tickers, "Weight": weights}).sort_values("Weight", ascending=False)
        for _, row in df.head(20).iterrows():
            pdf.cell(0, 5, f"    {row['Ticker']:12s}  {row['Weight']:.4f}  ({row['Weight']*100:.2f}%)", ln=True)

        pdf.ln(6)
        pdf.set_font("Courier", "I", 8)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 6, "Disclaimer: This report is for research purposes only and does not constitute investment advice.", ln=True)
        pdf.cell(0, 6, "Made by Sourish Dey | https://sourishdeyportfolio.vercel.app/", ln=True, align="C")

        return pdf.output()
    except ImportError:
        # Fallback: text file as bytes if fpdf2 not installed
        lines = [f"EigenPortfolio Report — {title}", "=" * 60]
        for strat, m in metrics_dict.items():
            lines.append(f"\n[{strat}]")
            for k, v in m.items():
                lines.append(f"  {k}: {v:.4f}" if isinstance(v, float) else f"  {k}: {v}")
        return "\n".join(lines).encode()


# ─── Portfolio Config ─────────────────────────────────────────────────────────

def save_portfolio_config(config: dict) -> str:
    """Serialize portfolio config to JSON string."""
    return json.dumps(config, indent=2, default=str)


def load_portfolio_config(json_str: str) -> dict:
    """Deserialize portfolio config from JSON string."""
    return json.loads(json_str)


# ─── Auto Insights ────────────────────────────────────────────────────────────

def generate_auto_insights(
    rmt_result,
    returns: pd.DataFrame,
    backtest_results: dict = None,
) -> list[str]:
    """
    Rule-based auto-generated quant insights from RMT and performance data.
    Returns a list of insight strings.
    """
    insights = []
    T, N = returns.shape

    # RMT insights
    signal_pct = rmt_result.n_signal / N * 100
    insights.append(
        f"📡 **RMT Signal Quality**: {rmt_result.n_signal} of {N} eigenvalues ({signal_pct:.1f}%) "
        f"exceed the Marchenko-Pastur upper bound (λ⁺ = {rmt_result.lambda_plus:.3f}), indicating "
        f"**{rmt_result.n_signal} genuine risk factors** in this universe."
    )

    if rmt_result.q < 2:
        insights.append(
            f"⚠️ **Low T/N Ratio (q={rmt_result.q:.2f})**: With only {T} observations for {N} assets, "
            f"the covariance matrix is poorly conditioned. RMT denoising is critical here."
        )
    else:
        insights.append(
            f"✅ **Adequate T/N Ratio (q={rmt_result.q:.2f})**: With {T} observations and {N} assets, "
            f"the covariance estimate is moderately reliable."
        )

    # Market factor
    eig0_var = rmt_result.eigenvalues[0] / rmt_result.eigenvalues.sum() * 100
    insights.append(
        f"🌍 **Market Factor (PC1)**: The dominant eigenvalue explains **{eig0_var:.1f}%** of total portfolio variance. "
        f"{'This is typical of a highly correlated market regime.' if eig0_var > 30 else 'Moderate market correlation — diversification opportunities exist.'}"
    )

    # Correlation insight
    avg_corr = (rmt_result.correlation_matrix.sum() - N) / (N * (N - 1))
    insights.append(
        f"🔗 **Average Pairwise Correlation**: {avg_corr:.3f}. "
        f"{'High correlation limits diversification benefits.' if avg_corr > 0.5 else 'Moderate diversification potential in this universe.'}"
    )

    # Backtest insights
    if backtest_results:
        best = max(backtest_results.items(), key=lambda x: x[1].sharpe)
        worst = min(backtest_results.items(), key=lambda x: x[1].sharpe)
        insights.append(
            f"🏆 **Best Strategy**: **{best[0]}** achieved the highest Sharpe ratio of {best[1].sharpe:.3f} "
            f"with CAGR of {best[1].cagr:.2%}."
        )
        insights.append(
            f"📉 **Deepest Drawdown**: **{worst[0]}** had the worst drawdown of {worst[1].max_drawdown:.2%}."
        )

    # Eigenportfolio concentration
    top3_var = rmt_result.eigenvalues[:3].sum() / rmt_result.eigenvalues.sum() * 100
    insights.append(
        f"📊 **Top-3 PCs Explain {top3_var:.1f}%** of total variance. "
        f"{'Highly concentrated factor structure.' if top3_var > 70 else 'Well-distributed factor structure.'}"
    )

    return insights


def generate_kpi_summary(
    rmt_result,
    returns: pd.DataFrame,
    backtest_results: dict | None = None,
) -> dict:
    """
    Structured KPI summary for the dashboard.
    Returns a dict suitable for KPI cards / AI prompting.
    """
    T, N = returns.shape
    denom_n = max(int(N), 1)
    ev_sum = float(np.sum(rmt_result.eigenvalues)) if hasattr(rmt_result, "eigenvalues") else 0.0
    ev_sum = max(ev_sum, 1e-12)

    signal_pct = (float(rmt_result.n_signal) / denom_n) * 100.0
    pc1_var_pct = (float(rmt_result.eigenvalues[0]) / ev_sum) * 100.0
    avg_corr = (rmt_result.correlation_matrix.sum() - N) / max(N * (N - 1), 1)
    top3_var_pct = (float(np.sum(rmt_result.eigenvalues[:3])) / ev_sum) * 100.0

    best_strategy = None
    best_sharpe = None
    best_cagr = None
    worst_drawdown_strategy = None
    worst_drawdown = None

    if backtest_results:
        best_name, best_res = max(backtest_results.items(), key=lambda x: x[1].sharpe)
        worst_dd_name, worst_dd_res = min(backtest_results.items(), key=lambda x: x[1].max_drawdown)
        best_strategy = best_name
        best_sharpe = float(best_res.sharpe)
        best_cagr = float(best_res.cagr)
        worst_drawdown_strategy = worst_dd_name
        worst_drawdown = float(worst_dd_res.max_drawdown)

    return {
        "assets_n": int(N),
        "observations_t": int(T),
        "q_t_over_n": float(rmt_result.q),
        "lambda_plus": float(rmt_result.lambda_plus),
        "lambda_max": float(rmt_result.lambda_max),
        "signal_pcs": int(rmt_result.n_signal),
        "signal_pct": float(signal_pct),
        "pc1_var_pct": float(pc1_var_pct),
        "avg_pairwise_corr": float(avg_corr),
        "top3_var_pct": float(top3_var_pct),
        "best_strategy": best_strategy,
        "best_sharpe": best_sharpe,
        "best_cagr": best_cagr,
        "worst_drawdown_strategy": worst_drawdown_strategy,
        "worst_drawdown": worst_drawdown,
    }


# ─── Research Mode Explanations ───────────────────────────────────────────────

RESEARCH_TEXTS = {
    "rmt_intro": """
### What is Random Matrix Theory (RMT)?

Random Matrix Theory provides a statistical benchmark for distinguishing **genuine correlations** 
from **noise** in large financial data matrices.

Given a T×N matrix of i.i.d. random returns, the eigenvalues of the resulting correlation 
matrix follow the **Marchenko-Pastur distribution** with bounds:

$$\\lambda_{\\pm} = \\sigma^2 \\left(1 \\pm \\frac{1}{\\sqrt{q}}\\right)^2, \\quad q = T/N$$

Eigenvalues **above λ⁺** carry genuine financial signal (e.g., market factor, sector factors).  
Eigenvalues **within** [λ⁻, λ⁺] are statistically indistinguishable from noise.
""",
    "eigenportfolio": """
### Eigenportfolios

An **eigenportfolio** is a long-only (or long-short) portfolio whose weights are proportional 
to an eigenvector of the correlation matrix.

- **PC1 (first eigenvector)** typically captures the **market factor** — all stocks move together.
- **PC2, PC3, ...** capture **sector or style factors** — long some sectors, short others.
- Eigenportfolios are **orthogonal** by construction: zero correlation between them.

This makes them excellent building blocks for **factor-based allocation strategies**.
""",
    "denoising": """
### RMT Covariance Denoising

The sample covariance matrix overestimates small eigenvalues and is sensitive to noise.  
RMT denoising replaces all **noise eigenvalues** (those within the MP band) with their average,  
preserving only the **signal subspace**.

This yields a **regularized covariance matrix** that:
- Has better condition number
- Produces more stable portfolio weights
- Reduces out-of-sample tracking error
""",
}
